//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="IdeaPOCO", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class IdeaPOCO : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string IdeaTextField;
    
    private string NameField;
    
    private int NameIdField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string IdeaText
    {
        get
        {
            return this.IdeaTextField;
        }
        set
        {
            this.IdeaTextField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Name
    {
        get
        {
            return this.NameField;
        }
        set
        {
            this.NameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int NameId
    {
        get
        {
            return this.NameIdField;
        }
        set
        {
            this.NameIdField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISytech")]
public interface ISytech
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISytech/GetIdeas", ReplyAction="http://tempuri.org/ISytech/GetIdeasResponse")]
    IdeaPOCO[] GetIdeas();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISytech/GetIdeas", ReplyAction="http://tempuri.org/ISytech/GetIdeasResponse")]
    System.Threading.Tasks.Task<IdeaPOCO[]> GetIdeasAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISytech/SaveIdea", ReplyAction="http://tempuri.org/ISytech/SaveIdeaResponse")]
    void SaveIdea(string ideaText, string personId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISytech/SaveIdea", ReplyAction="http://tempuri.org/ISytech/SaveIdeaResponse")]
    System.Threading.Tasks.Task SaveIdeaAsync(string ideaText, string personId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISytech/GetPeople", ReplyAction="http://tempuri.org/ISytech/GetPeopleResponse")]
    WCFREST.PeoplePOCO[] GetPeople();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISytech/GetPeople", ReplyAction="http://tempuri.org/ISytech/GetPeopleResponse")]
    System.Threading.Tasks.Task<WCFREST.PeoplePOCO[]> GetPeopleAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISytechChannel : ISytech, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SytechClient : System.ServiceModel.ClientBase<ISytech>, ISytech
{
    
    public SytechClient()
    {
    }
    
    public SytechClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SytechClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SytechClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SytechClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public IdeaPOCO[] GetIdeas()
    {
        return base.Channel.GetIdeas();
    }
    
    public System.Threading.Tasks.Task<IdeaPOCO[]> GetIdeasAsync()
    {
        return base.Channel.GetIdeasAsync();
    }
    
    public void SaveIdea(string ideaText, string personId)
    {
        base.Channel.SaveIdea(ideaText, personId);
    }
    
    public System.Threading.Tasks.Task SaveIdeaAsync(string ideaText, string personId)
    {
        return base.Channel.SaveIdeaAsync(ideaText, personId);
    }
    
    public WCFREST.PeoplePOCO[] GetPeople()
    {
        return base.Channel.GetPeople();
    }
    
    public System.Threading.Tasks.Task<WCFREST.PeoplePOCO[]> GetPeopleAsync()
    {
        return base.Channel.GetPeopleAsync();
    }
}
namespace WCFREST
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeoplePOCO", Namespace="http://schemas.datacontract.org/2004/07/WCFREST")]
    public partial class PeoplePOCO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FirstNameField;
        
        private int IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
}
